!
! =========================================================
! Device: sw-1
! Role  : Access Switch (Layer 2)
!
! Connected to:
! - phede-1 (Distribution)
! - phede-2 (Distribution)
!
! Features:
! - VLAN segmentation
! - RSTP
! - EtherChannel (LACP)
! - VTP Client
! =========================================================
!

hostname sw-1

! ---------------- VLAN CONFIGURATION ----------------
vlan 10
 name RG
vlan 20
 name MARKETING
vlan 30
 name DRH
vlan 40
 name GUEST

! ---------------- SPANNING TREE ----------------
spanning-tree mode rapid-pvst

! ---------------- ETHERCHANNEL TO DISTRIBUTION ----------------
interface range Ethernet0/0 - 1
 channel-protocol lacp
 channel-group 1 mode active
 no shutdown

interface Port-channel1
 switchport mode trunk
 switchport trunk allowed vlan 1,10,20,30,40

interface range Ethernet0/2 - 3
 channel-protocol lacp
 channel-group 2 mode active
 no shutdown

interface Port-channel2
 switchport mode trunk
 switchport trunk allowed vlan 1,10,20,30,40

! ---------------- ACCESS PORTS ----------------
interface range Ethernet0/4 - 7
 switchport mode access
 switchport access vlan 10
 description USERS_RG
 no shutdown

interface range Ethernet0/8 - 11
 switchport mode access
 switchport access vlan 20
 description USERS_MARKETING
 no shutdown

interface range Ethernet0/12 - 15
 switchport mode access
 switchport access vlan 30
 description USERS_DRH
 no shutdown

interface range Ethernet0/16 - 19
 switchport mode access
 switchport access vlan 40
 description USERS_GUEST
 no shutdown

! ---------------- VTP ----------------
vtp domain CPS-LAB
vtp mode client
vtp password cisco
vtp version 2

